### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [zyachel/libremdb#12]
Excuse me but how I use it?? normally in nitter or any other software you can replace URLs but for some reason when I do it here I get 404 page so how am I supposed to use it?

**Comment by zyachel** [comment]
for now, just one route works, i.e., `/title/movie-id`.  
other routes like lists are in works.

**Comment by EsmailELBoBDev2** [comment]
No, it was movie and this is the thing now after I test it again it works (for whatever reason it used to throw 404) but now it's not so all good!
