### ISSUE TITLE
Add "More like this" section 

### ISSUE THREAD

**Issue by ericpa06** [zyachel/libremdb#14]
Hi, first of all, I just wanted to congratulate you for the project, it's pretty nice and useful, especially due to how bloated the web has become lately. With that said, it would be nice if your project also included the "similar" section on the alternative imdb front-end. Many people, including myself, use imdb as a way to find similar movies to one movie that we liked it.
![image](https://user-images.githubusercontent.com/6937720/183542516-33f2f869-9c23-4b72-a13b-3b1374788b38.png)

**Comment by zyachel** [comment]
Hey there, and thanks! I really appreciate your encouragement.

I recently got a way to extract almost all data on movie info page, including trailer videos, and 'more like this' :).

And thus, I am planning a whole rewrite of this application, as with more pages, CSS and components are going to grow fast. I am thinking of rewriting everything in Next.js, as it makes a bit easy(for me) to manage separate components and CSS. This rewrite will delay the implementation of other routes(like search and reviews), but I think will help to manage the project in the long run.

So, all in all, you can stick to IMDb for the time being. I'll hopefully complete this rewrite soon.

**Comment by ericpa06** [comment]
Cool! Thank you very much :)

**Comment by 2084x** [comment]
> I recently got a way to extract almost all data on movie info page, including trailer videos, and 'more like this' :).
Is the user added parental advisory section included in that info? it's basically the only reason I use imdb. if you could find a way to add that and implement searching your site would be perfect!

**Comment by zyachel** [comment]
@ericpa06, it was added in e4849e8c757e4f1416be7338c89421ca27e28e8d.  

![image](https://user-images.githubusercontent.com/97783235/189574592-8b9a85f5-b762-4cdd-950d-f397dc29b47a.png)  

you can see it live at https://libremdb.iket.me/title/tt2151454

**Comment by zyachel** [comment]
@2084x, there is a small info bar just below the title that includes rating.  

![image](https://user-images.githubusercontent.com/97783235/189575254-75a2a7bd-9aec-4a50-ae91-9e8f2f9ca0aa.png)

But if you're talking about a dedicated route(like this: https://www.imdb.com/title/tt0296572/parentalguide), then it is not implemented yet.  

I'll add it to to-do list. You can continue using IMDb for the time being.

**Comment by 2084x** [comment]
> But if you're talking about a dedicated route(like this: https://www.imdb.com/title/tt0296572/parentalguide),

That's the one I was talking about. Thanks for adding it to the to do list.

**Comment by ericpa06** [comment]
> @ericpa06, it was added in [e4849e8](https://github.com/zyachel/libremdb/commit/e4849e8c757e4f1416be7338c89421ca27e28e8d).
> 
> ![image](https://user-images.githubusercontent.com/97783235/189574592-8b9a85f5-b762-4cdd-950d-f397dc29b47a.png)
> 
> you can see it live at https://libremdb.iket.me/title/tt2151454

Thank you so much :) It's absolutely perfect. Now I have no reason to go to imdb at all 😂

**Comment by ericpa06** [comment]
Just another humble suggestion. Maybe it would be interesting if the this section was displayed in multiple rows rather than a single scrollable roll. Something like, I think this could improve the easy of use. 🤔

![image](https://user-images.githubusercontent.com/6937720/191415094-a6e3f6e0-a580-4525-83c5-af193a28c774.png)
