### ISSUE TITLE
Redirect unsupported paths to TMDB or OMDB.

### ISSUE THREAD

**Issue by MintMain21** [zyachel/libremdb#23]
Until there is official support for paths such as search or cast/crew, it may be handy to redirect to one of those IMDB alternatives instead of loading a error page.

**Comment by zyachel** [comment]
I could at best redirect to search results for the given title name. since TMDB has different slug for titles than what IMDb has.

**Comment by MintMain21** [comment]
I think with all the updates to Libremdb, this is irrelevant.
