### ISSUE TITLE
Users' reviews and libremdb

### ISSUE THREAD

**Issue by Lippiece** [zyachel/libremdb#25]
Every instance I tried using to see the user reviews for any movie resulted in 404. [For example](https://ld.vern.cc/title/tt7631058/reviews).

Is there no support for this and if that's the case is this feature planned?

**Comment by zyachel** [comment]
it hasn't been implemented yet, but is in the [to-do list](https://github.com/zyachel/libremdb#to-do).

**Comment by jneidel** [comment]
Perfect! Thank you for your effort @zyachel!
