### ISSUE TITLE
Videos can't be fast forwarded 

### ISSUE THREAD

**Issue by ghost** [zyachel/libremdb#26]
When I watch a trailer I can't advance a video. The seek bar just snaps back to the current timestamp.

**Comment by zyachel** [comment]
can you show me an example(possibly with browser specification)?

**Comment by helpthemfix** [comment]
When I try to watch the trailer I can't advance it as seen here `https://libremdb.iket.me/title/tt0144084`

I'm on Windows 10 using Brave browser version 108
