### ISSUE TITLE
Profile of a person missing

### ISSUE THREAD

**Issue by airone506** [zyachel/libremdb#36]
This is probably the last feature I'm missing in libremdb. So let's consider this to be a polite feature suggestion.

A profile of a person can not be displayed, "Not found, sorry. (404)" page appears. E.g.:
https://www.imdb.com/name/nm0000086/

EDIT 1:
Already mentioned here:
https://github.com/zyachel/libremdb/issues/30#issuecomment-1405291790

**Comment by zyachel** [comment]
yes, it's the one I'm working on right now.

**Comment by zyachel** [comment]
added in v3
