### ISSUE TITLE
500 error on searching

### ISSUE THREAD

**Issue by aeternum1986** [zyachel/libremdb#37]
Hello

When I try searching on Libremdb, it gives me a 500 error.  there's nothing useful in the logs. I tried it on a different server, and it does the same thing. Any ideas?

**Comment by aeternum1986** [comment]
I should also note, I am using docker, and the docker image is the pussthecat image.

**Comment by zyachel** [comment]
There are a couple of [required env vars](https://github.com/zyachel/libremdb/blob/main/.env.local.example) that pussthecat's image doesn't have.  
That is most likely the issue.  
Can you build an image with those vars and test if it works?

**Comment by aeternum1986** [comment]
aha. it worked. Thanks so much :)
