### ISSUE TITLE
Actors' pages

### ISSUE THREAD

**Issue by aeternum1986** [zyachel/libremdb#39]
Hello

so I came into a problem whereby on every instance I've found, the actor pages don't load. they 404. e.g. [here](https://libremdb.iket.me/name/nm4529842) Is this a known problem?

**Comment by zyachel** [comment]
Yes, the person's info page is in the works.  
Bear with me for a couple of weeks as I finish the UI.

**Comment by aeternum1986** [comment]
no worries. Just wanted to check with you if you knew about it.
