### ISSUE TITLE
Where is sadgnu.svg from?

### ISSUE THREAD

**Issue by ndren** [zyachel/libremdb#41]
Hi,

I saw sadgnu.svg (on an error page: https://libremdb.iket.me/error) and I really loved the art. Is it by the same artist as https://www.gnu.org/graphics/sventsitsky-sadgnu.html? I'd love to know!

Thanks!

**Comment by zyachel** [comment]
hey there!
yes, it's from the link you shared, as can be seen from the source code:  

https://github.com/zyachel/libremdb/blob/86737c51eec23bb00990be841dde4262f39519ca/src/components/error/ErrorInfo.tsx#L7-L9  

https://github.com/zyachel/libremdb/blob/86737c51eec23bb00990be841dde4262f39519ca/public/svg/sadgnu.svg?short_path=80be29c#L3-L8  

I've just remixed the original to svg with inkscape. Feel free to use it.  
And remember, thank GNU :)
