### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [zyachel/libremdb#47]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `libremdb.esmailelbob.xyz` / `libremdb.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: ~~https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a~~ -> https://web.archive.org/web/20230522041632/https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by zyachel** [comment]
Since this issue is exact same as  https://github.com/zyachel/quetre/issues/107, please see my response over there.
