### ISSUE TITLE
404 of pages not yet implemented should redirect to imdb

### ISSUE THREAD

**Issue by Cwpute** [zyachel/libremdb#50]
When searching for some imdb pages this project currently doesn't support, we're taken to a 404 page. It's ok not to have everything covered, but the original url of the page we were going for is lost in the process. Sure there is a pop-up button on the toolbar up there to go to the corresponding imdb page... but it takes you to `https://www.imdb.com/404`... eheh.

See for yourself the `Characters` sections on a Series page:

- original link: https://www.imdb.com/title/tt12217196/characters/nm9627126
- libremdb link: https://libremdb.iket.me/title/tt12217196/characters/nm9627126

libremdb should retain the original imdb url you were going for, and for pages it doesn't cover yet, give users the opportunity to browse that exact page over at the original website.

This would be especially useful for people like mewho have activated redirectors like LibRedirect and can have a hard time accessing the original website's page

**Comment by zyachel** [comment]
Thanks for the issue!

This seems to be a limitation of Next.js(the framework I'm using for libremdb). I'll fix it.
