### ISSUE TITLE
something went wrong (500)

### ISSUE THREAD

**Issue by riveravaldez** [zyachel/libremdb#51]
Hi, I'm having issue's title as message when trying to load this page:

https://libremdb.iket.me/name/nm0685856

I'm using F-Droid's Fennec browser over LineageOS (Android 10 equivalent) on an old Moto E LTE (surnia) 2015.

Just reporting. Please let me know if I could provide any useful information.

Thanks a lot!

**Comment by zyachel** [comment]
I'll look into this. thanks for reporting!

**Comment by riveravaldez** [comment]
On the contrary, thanks a lot for your great work.
Lightweight (and/or static) WebUI are an absolutely needed bless for old hardware...
Now the website it's working fine both in desktop and mobile, just checked, ¡thanks a lot!
Kind regards.

**Comment by zyachel** [comment]
glad you find it useful :)

**Comment by sergeevabc** [comment]
Checked on a dozen instances, everywhere I get this same 500 error when trying to open some film's about page. For example, https://libremdb.lunar.icu/title/tt14030816

**Comment by zyachel** [comment]
I'll look into it. thanks for sharing. though you can always create a new issue :)
