### ISSUE TITLE
Include a version

### ISSUE THREAD

**Issue by grandeljay** [zyachel/libremdb#59]
Hello, thank you for making this!

I just stumbled over here and noticed there was a new release recently. How can I see if a hosted instance already has updated or which version they are running?

In case it's not possible: please add a version somewhere (maybe the about page).

**Comment by grandeljay** [comment]
Thank you! I was so sure that I checked that page but I obviously missed it.

**Comment by zyachel** [comment]
no worries. glad you find the service useful.
