### ISSUE TITLE
fix instances.json

### ISSUE THREAD

**Issue by Topmay** [zyachel/libremdb#72]
The instances.json file has an extra https:// in front of the urls. This is preventing browser extensions such as libredirect from correctly fetching the url. I would open a pull request myself but I don't know how :)

**Comment by zyachel** [comment]
sorry, didn't see it before merging https://github.com/zyachel/libremdb/pull/71  
will fix it!

**Comment by zyachel** [comment]
thanks!  
you can fork the repo, make changes, update your fork, and then create a pr. [more here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
