### ISSUE TITLE
500 ISE All Instances

### ISSUE THREAD

**Issue by dfuentes87** [zyachel/libremdb#83]
I think IMDB changed something just recently, all instances are showing 500 ISE for any movie:
https://libremdb.iket.me/title/tt0080569
https://libremdb.pussthecat.org/title/tt1392190
https://libremdb.lunar.icu/title/tt3062074
https://imdb.nerdvpn.de/title/tt0105941

<img width="1046" alt="Screenshot 2024-08-21 at 7 48 17 PM" src="https://github.com/user-attachments/assets/d9d6d427-e022-497d-829d-5cff9bab5bfa">

**Comment by zyachel** [comment]
thanks for informing! I'll look into it.

**Comment by zyachel** [comment]
i've added a fix(on my instance), let me know if it works for you

**Comment by dfuentes87** [comment]
Yes, your instance is working for me now.

**Comment by zyachel** [comment]
sorry @Sommerwiesel, I forgot to push the changes before.
