### ISSUE TITLE
Third party streaming

### ISSUE THREAD

**Issue by AykhanUV** [zyachel/libremdb#85]
You should add third party streaming from vidsrc

**Comment by zyachel** [comment]
as in watching movies directly on the website?

**Comment by AykhanUV** [comment]
Yeah exactly

**Comment by zyachel** [comment]
That'd be one way to shut down this project quickly, mate.  
Also, that's a big feature creep. I haven't even been able to add basic features for almost a year now, so, that's a no from me. I hope you understand.
